# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinanceDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveObjC', '~> 3.1.1'

  # Pods for FinanceDemo

  target 'FinanceDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinanceDemoUITests' do
    # Pods for testing
  end

end
